/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Address: typeof import('./../src/components/Address.vue')['default']
    ChineseName: typeof import('./../src/components/ChineseName.vue')['default']
    CompanyName: typeof import('./../src/components/CompanyName.vue')['default']
    CreditCode: typeof import('./../src/components/CreditCode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElText: typeof import('element-plus/es')['ElText']
    Email: typeof import('./../src/components/Email.vue')['default']
    GeneratesAll: typeof import('./../src/components/GeneratesAll.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IdentifyNumber: typeof import('./../src/components/IdentifyNumber.vue')['default']
    PhoneNumber: typeof import('./../src/components/PhoneNumber.vue')['default']
  }
}
